language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      dist: trusty
    - os: linux
      rust: stable
      dist: trusty
    - os: osx
      rust: nightly
    - os: osx
      rust: stable
sudo: true
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
script:
  - rustc --version
  - RUST_BACKTRACE=1 cargo build
  - RUST_BACKTRACE=1 cargo build --no-default-features
  - RUST_BACKTRACE=1 cargo test
